kinase_mapping = {'AGC': 0,
                  'AGC AKT': 1,
                  'AGC AKT AKT1': 2,
                  'AGC DMPK': 3,
                  'AGC DMPK ROCK': 4,
                  'AGC DMPK ROCK ROCK1': 5,
                  'AGC DMPK ROCK ROCK2': 6,
                  'AGC GRK': 7,
                  'AGC GRK GRK2': 8,
                  'AGC NDR': 9,
                  'AGC PKA': 10,
                  'AGC PKA PKACa': 11,
                  'AGC PKB': 12,
                  'AGC PKB PDK1': 13,
                  'AGC PKC': 14,
                  'AGC PKC Alpha': 15,
                  'AGC PKC Alpha PKCa': 16,
                  'AGC PKC Alpha PKCb': 17,
                  'AGC PKC Delta': 18,
                  'AGC PKC Delta PKCd': 19,
                  'AGC PKC Delta PKCt': 20,
                  'AGC PKC Eta': 21,
                  'AGC PKC Eta PKCe': 22,
                  'AGC PKC Iota': 23,
                  'AGC PKC Iota PKCz': 24,
                  'AGC PKG': 25,
                  'AGC PKG PKG1': 26,
                  'AGC RSK': 27,
                  'AGC RSK MSK': 28,
                  'AGC RSK MSK MSK1': 29,
                  'AGC RSK RSK': 32,
                  'AGC RSK RSK RSK2': 33,
                  'AGC RSK p70': 30,
                  'AGC RSK p70 p70S6K': 31,
                  'AGC SGK': 34,
                  'Atypical': 35,
                  'Atypical PIKK': 36,
                  'Atypical PIKK ATM': 37,
                  'Atypical PIKK ATR': 38,
                  'Atypical PIKK DNAPK': 39,
                  'Atypical PIKK FRAP': 40,
                  'Atypical PIKK FRAP TOR': 41,
                  'CAMK': 42,
                  'CAMK CAMK1': 43,
                  'CAMK CAMK1 CAMK1A': 44,
                  'CAMK CAMK2': 45,
                  'CAMK CAMKL': 46,
                  'CAMK CAMKL AMPK': 47,
                  'CAMK CAMKL AMPK AMPKa1': 48,
                  'CAMK CAMKL CHK1': 49,
                  'CAMK CAMKL CHK1 CHK1': 50,
                  'CAMK CAMKL LKB': 51,
                  'CAMK CAMKL LKB LKB1': 52,
                  'CAMK CAMKL MARK': 53,
                  'CAMK DAPK': 54,
                  'CAMK MAPKAPK': 55,
                  'CAMK MAPKAPK MAPKAPK': 56,
                  'CAMK MAPKAPK MAPKAPK MAPKAPK2': 57,
                  'CAMK PIM': 58,
                  'CAMK PKD': 59,
                  'CAMK PKD PKD1': 60,
                  'CAMK RAD53': 61,
                  'CAMK RAD53 CHK2': 62,
                  'CK1': 63,
                  'CK1 CK1': 64,
                  'CK1 VRK': 65,
                  'CMGC': 66,
                  'CMGC CDK': 67,
                  'CMGC CDK CDK1/CDC2': 68,
                  'CMGC CDK CDK2': 69,
                  'CMGC CDK CDK4': 70,
                  'CMGC CDK CDK5': 71,
                  'CMGC CDK CDK7': 72,
                  'CMGC CDK CDK9': 73,
                  'CMGC DYRK': 74,
                  'CMGC DYRK Dyrk1': 75,
                  'CMGC DYRK Dyrk2': 76,
                  'CMGC DYRK Dyrk2 DYRK2': 77,
                  'CMGC DYRK HIPK': 78,
                  'CMGC DYRK HIPK HIPK2': 79,
                  'CMGC GSK': 80,
                  'CMGC GSK GSK3A': 81,
                  'CMGC GSK GSK3B': 82,
                  'CMGC MAPK': 83,
                  'CMGC MAPK ERK': 84,
                  'CMGC MAPK ERK Erk1': 85,
                  'CMGC MAPK ERK Erk2': 86,
                  'CMGC MAPK JNK': 87,
                  'CMGC MAPK JNK JNK1': 88,
                  'CMGC MAPK JNK JNK2': 89,
                  'CMGC MAPK p38': 90,
                  'CMGC MAPK p38 p38a': 91,
                  'Other': 92,
                  'Other AUR': 93,
                  'Other AUR AurA': 94,
                  'Other AUR AurB': 95,
                  'Other CK2': 96,
                  'Other CK2 CK2a1': 97,
                  'Other IKK': 98,
                  'Other IKK IKKa': 99,
                  'Other IKK IKKb': 100,
                  'Other IKK TBK1': 101,
                  'Other NEK': 102,
                  'Other PLK': 103,
                  'Other PLK PLK1': 104,
                  'Other PLK PLK2': 105,
                  'Other PLK PLK3': 106,
                  'Other ULK': 107,
                  'Other ULK ULK1': 108,
                  'PKL': 109,
                  'PKL FJ': 110,
                  'PKL FJ FAM': 111,
                  'PKL FJ FAM FAM20C': 112,
                  'STE': 113,
                  'STE STE11': 114,
                  'STE STE20': 115,
                  'STE STE20 MST': 116,
                  'STE STE20 MST MST1': 117,
                  'STE STE20 PAKA': 118,
                  'STE STE20 PAKA PAK1': 119,
                  'STE STE20 PAKA PAK2': 120,
                  'STE STE7': 121,
                  'TK': 122,
                  'TK Abl': 123,
                  'TK Abl ABL': 124,
                  'TK Csk': 125,
                  'TK Csk CSK': 126,
                  'TK EGFR': 127,
                  'TK EGFR EGFR': 128,
                  'TK FGFR': 131,
                  'TK Fak': 129,
                  'TK Fak FAK': 130,
                  'TK InsR': 132,
                  'TK InsR INSR': 133,
                  'TK Jak': 134,
                  'TK Jak JAK2': 135,
                  'TK PDGFR': 136,
                  'TK Src': 137,
                  'TK Src FYN': 138,
                  'TK Src LCK': 139,
                  'TK Src LYN': 140,
                  'TK Syk': 141,
                  'TK Syk SYK': 142,
                  'TK Tec': 143,
                  'TKL': 144,
                  'TKL LRRK': 145,
                  'TKL LRRK LRRK2': 146,
                  'TKL MLK': 147,
                  'TKL RAF': 148,
                  'TKL STKR': 149}

kinase_mapping_reverse = {0: 'AGC',
                          1: 'AGC AKT',
                          2: 'AGC AKT AKT1',
                          3: 'AGC DMPK',
                          4: 'AGC DMPK ROCK',
                          5: 'AGC DMPK ROCK ROCK1',
                          6: 'AGC DMPK ROCK ROCK2',
                          7: 'AGC GRK',
                          8: 'AGC GRK GRK2',
                          9: 'AGC NDR',
                          10: 'AGC PKA',
                          11: 'AGC PKA PKACa',
                          12: 'AGC PKB',
                          13: 'AGC PKB PDK1',
                          14: 'AGC PKC',
                          15: 'AGC PKC Alpha',
                          16: 'AGC PKC Alpha PKCa',
                          17: 'AGC PKC Alpha PKCb',
                          18: 'AGC PKC Delta',
                          19: 'AGC PKC Delta PKCd',
                          20: 'AGC PKC Delta PKCt',
                          21: 'AGC PKC Eta',
                          22: 'AGC PKC Eta PKCe',
                          23: 'AGC PKC Iota',
                          24: 'AGC PKC Iota PKCz',
                          25: 'AGC PKG',
                          26: 'AGC PKG PKG1',
                          27: 'AGC RSK',
                          28: 'AGC RSK MSK',
                          29: 'AGC RSK MSK MSK1',
                          30: 'AGC RSK p70',
                          31: 'AGC RSK p70 p70S6K',
                          32: 'AGC RSK RSK',
                          33: 'AGC RSK RSK RSK2',
                          34: 'AGC SGK',
                          35: 'Atypical',
                          36: 'Atypical PIKK',
                          37: 'Atypical PIKK ATM',
                          38: 'Atypical PIKK ATR',
                          39: 'Atypical PIKK DNAPK',
                          40: 'Atypical PIKK FRAP',
                          41: 'Atypical PIKK FRAP TOR',
                          42: 'CAMK',
                          43: 'CAMK CAMK1',
                          44: 'CAMK CAMK1 CAMK1A',
                          45: 'CAMK CAMK2',
                          46: 'CAMK CAMKL',
                          47: 'CAMK CAMKL AMPK',
                          48: 'CAMK CAMKL AMPK AMPKa1',
                          49: 'CAMK CAMKL CHK1',
                          50: 'CAMK CAMKL CHK1 CHK1',
                          51: 'CAMK CAMKL LKB',
                          52: 'CAMK CAMKL LKB LKB1',
                          53: 'CAMK CAMKL MARK',
                          54: 'CAMK DAPK',
                          55: 'CAMK MAPKAPK',
                          56: 'CAMK MAPKAPK MAPKAPK',
                          57: 'CAMK MAPKAPK MAPKAPK MAPKAPK2',
                          58: 'CAMK PIM',
                          59: 'CAMK PKD',
                          60: 'CAMK PKD PKD1',
                          61: 'CAMK RAD53',
                          62: 'CAMK RAD53 CHK2',
                          63: 'CK1',
                          64: 'CK1 CK1',
                          65: 'CK1 VRK',
                          66: 'CMGC',
                          67: 'CMGC CDK',
                          68: 'CMGC CDK CDK1/CDC2',
                          69: 'CMGC CDK CDK2',
                          70: 'CMGC CDK CDK4',
                          71: 'CMGC CDK CDK5',
                          72: 'CMGC CDK CDK7',
                          73: 'CMGC CDK CDK9',
                          74: 'CMGC DYRK',
                          75: 'CMGC DYRK Dyrk1',
                          76: 'CMGC DYRK Dyrk2',
                          77: 'CMGC DYRK Dyrk2 DYRK2',
                          78: 'CMGC DYRK HIPK',
                          79: 'CMGC DYRK HIPK HIPK2',
                          80: 'CMGC GSK',
                          81: 'CMGC GSK GSK3A',
                          82: 'CMGC GSK GSK3B',
                          83: 'CMGC MAPK',
                          84: 'CMGC MAPK ERK',
                          85: 'CMGC MAPK ERK Erk1',
                          86: 'CMGC MAPK ERK Erk2',
                          87: 'CMGC MAPK JNK',
                          88: 'CMGC MAPK JNK JNK1',
                          89: 'CMGC MAPK JNK JNK2',
                          90: 'CMGC MAPK p38',
                          91: 'CMGC MAPK p38 p38a',
                          92: 'Other',
                          93: 'Other AUR',
                          94: 'Other AUR AurA',
                          95: 'Other AUR AurB',
                          96: 'Other CK2',
                          97: 'Other CK2 CK2a1',
                          98: 'Other IKK',
                          99: 'Other IKK IKKa',
                          100: 'Other IKK IKKb',
                          101: 'Other IKK TBK1',
                          102: 'Other NEK',
                          103: 'Other PLK',
                          104: 'Other PLK PLK1',
                          105: 'Other PLK PLK2',
                          106: 'Other PLK PLK3',
                          107: 'Other ULK',
                          108: 'Other ULK ULK1',
                          109: 'PKL',
                          110: 'PKL FJ',
                          111: 'PKL FJ FAM',
                          112: 'PKL FJ FAM FAM20C',
                          113: 'STE',
                          114: 'STE STE11',
                          115: 'STE STE20',
                          116: 'STE STE20 MST',
                          117: 'STE STE20 MST MST1',
                          118: 'STE STE20 PAKA',
                          119: 'STE STE20 PAKA PAK1',
                          120: 'STE STE20 PAKA PAK2',
                          121: 'STE STE7',
                          122: 'TK',
                          123: 'TK Abl',
                          124: 'TK Abl ABL',
                          125: 'TK Csk',
                          126: 'TK Csk CSK',
                          127: 'TK EGFR',
                          128: 'TK EGFR EGFR',
                          129: 'TK Fak',
                          130: 'TK Fak FAK',
                          131: 'TK FGFR',
                          132: 'TK InsR',
                          133: 'TK InsR INSR',
                          134: 'TK Jak',
                          135: 'TK Jak JAK2',
                          136: 'TK PDGFR',
                          137: 'TK Src',
                          138: 'TK Src FYN',
                          139: 'TK Src LCK',
                          140: 'TK Src LYN',
                          141: 'TK Syk',
                          142: 'TK Syk SYK',
                          143: 'TK Tec',
                          144: 'TKL',
                          145: 'TKL LRRK',
                          146: 'TKL LRRK LRRK2',
                          147: 'TKL MLK',
                          148: 'TKL RAF',
                          149: 'TKL STKR'}
